#ifndef VSGL2_KEYCODE_H_INCLUDED
#define VSGL2_KEYCODE_H_INCLUDED

const int VSGL_0 = SDL_SCANCODE_0;
const int VSGL_1 = SDL_SCANCODE_1;
const int VSGL_2 = SDL_SCANCODE_2;
const int VSGL_3 = SDL_SCANCODE_3;
const int VSGL_4 = SDL_SCANCODE_4;
const int VSGL_5 = SDL_SCANCODE_5;
const int VSGL_6 = SDL_SCANCODE_6;
const int VSGL_7 = SDL_SCANCODE_7;
const int VSGL_8 = SDL_SCANCODE_8;
const int VSGL_9 = SDL_SCANCODE_9;

const int VSGL_A = SDL_SCANCODE_A;
const int VSGL_B = SDL_SCANCODE_B;
const int VSGL_C = SDL_SCANCODE_C;
const int VSGL_D = SDL_SCANCODE_D;
const int VSGL_E = SDL_SCANCODE_E;
const int VSGL_F = SDL_SCANCODE_F;
const int VSGL_G = SDL_SCANCODE_G;
const int VSGL_H = SDL_SCANCODE_H;
const int VSGL_I = SDL_SCANCODE_I;
const int VSGL_J = SDL_SCANCODE_J;
const int VSGL_K = SDL_SCANCODE_K;
const int VSGL_L = SDL_SCANCODE_L;
const int VSGL_M = SDL_SCANCODE_M;
const int VSGL_N = SDL_SCANCODE_N;
const int VSGL_O = SDL_SCANCODE_O;
const int VSGL_P = SDL_SCANCODE_P;
const int VSGL_Q = SDL_SCANCODE_Q;
const int VSGL_R = SDL_SCANCODE_R;
const int VSGL_S = SDL_SCANCODE_S;
const int VSGL_T = SDL_SCANCODE_T;
const int VSGL_U = SDL_SCANCODE_U;
const int VSGL_V = SDL_SCANCODE_V;
const int VSGL_W = SDL_SCANCODE_W;
const int VSGL_X = SDL_SCANCODE_X;
const int VSGL_Y = SDL_SCANCODE_Y;
const int VSGL_Z = SDL_SCANCODE_Z;

const int VSGL_LEFT = SDL_SCANCODE_LEFT;
const int VSGL_RIGHT = SDL_SCANCODE_RIGHT;
const int VSGL_UP = SDL_SCANCODE_UP;
const int VSGL_DOWN = SDL_SCANCODE_DOWN;

#endif //VSGL2_KEYCODE_H_INCLUDED
