#ifndef VSGL2_KEYCODE_H_INCLUDED
#define VSGL2_KEYCODE_H_INCLUDED

const int VSGL_a = SDL_SCANCODE_A;
const int VSGL_LEFT = SDL_SCANCODE_LEFT;
const int VSGL_RIGHT = SDL_SCANCODE_RIGHT;
const int VSGL_UP = SDL_SCANCODE_UP;
const int VSGL_DOWN = SDL_SCANCODE_DOWN;

#endif //VSGL2_KEYCODE_H_INCLUDED
